### ISSUE TITLE
Differences from https://github.com/nickcharron/waypoint_nav?

### ISSUE THREAD

**Issue by nickcharron** [ArghyaChatterjee/gps-waypoint-based-autonomous-navigation-in-ros#1]
Hi, this package looks very similar to https://github.com/nickcharron/waypoint_nav

Can you comment on what changes you've made? Any improvements or bug fixes?

Thanks!

**Comment by ArghyaChatterjee** [comment]
HI @nickcharron, I haven't updated the repo for quite a while. I was working for a competition back then and most of my work was private. I have customized (rover, sensor, dev. platform, ui etc.) your repo to use it with our rover. I could not disclose it at that time as it was part of a competition. I will update the repo soon with our version.

**Comment by ArghyaChatterjee** [comment]
Closing the issue !!

**Comment by nickcharron** [comment]
Okay thanks! If you could just highlight the differences between the two in your docs that would be great.
