### ISSUE TITLE
Trying to get this to work in a rosject

### ISSUE THREAD

**Issue by skysingh** [ArghyaChatterjee/gps-waypoint-based-autonomous-navigation-in-ros#2]
I am quite interested in this work in order to develop an agricultural robot. I was trying to get it installed in a rosject sim in theconstruct so I can work with a simulation. I got the catkin_make to compile without errors but I cannot get the launch to work. Error is :

[gps_waypoint_nav.launch] is neither a launch file in package [gps_waypoint_nav] nor is [gps_waypoint_nav] a launch file name
The traceback for the exception was written to the log file

**Comment by Sylvania2** [comment]
Hi

Project is named outdoor_waypoint_nav in CMakelists.txt try: 
roslaunch outdoor_waypoint_nav gps_waypoint_nav.launch

Launch files also needs to be edited to $(find outdoor_waypoint_nav).

Best regards Kim

**Comment by ArghyaChatterjee** [comment]
The problem has been solved. Sorry I didn't have enough time as I was busy with my projects. Just do a fresh clone on ros melodic and follow the instruction for build from the readme file.
