### ISSUE TITLE
Cannot run gps_waypoint_nav.launch

### ISSUE THREAD

**Issue by khinggan** [ArghyaChatterjee/gps-waypoint-based-autonomous-navigation-in-ros#3]
Hi, 
     I want to test run your repository on the ROS melodic Ubuntu 18.04LTS,  NVIDIA Jetson TX2. I followed your README doc, and I sacked when run the `roslaunch gps_waypoint_nav gps_waypoint_nav.launch`. The error message is RLException: [gps_waypoint_nav.launch] is neither a launch file in package [gps_waypoint_nav] nor is [gps_waypoint_nav] a launch file name
The traceback for the exception was written to the log file
 
Thanks

**Comment by hsaleem1** [comment]
Hi @khinggan,

I got the same error. Could you please guide me how you resolved this error?

Thanks for your help.
