### ISSUE TITLE
Catkin make error

### ISSUE THREAD

**Issue by KoushikRaghav** [ArghyaChatterjee/gps-waypoint-based-autonomous-navigation-in-ros#4]
Cloned the repo and ran catkin_make

CMakeFiles/Makefile2:609: recipe for target 'gps-waypoint-based-autonomous-navigation-in-ros/CMakeFiles/gps_waypoint_continuous2.dir/all' failed
make[1]: *** [gps-waypoint-based-autonomous-navigation-in-ros/CMakeFiles/gps_waypoint_continuous2.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

Getting this error. Please help to fix this

**Comment by RamanaBotta** [comment]
the same problem , have you solved it.

**Comment by salbatarni** [comment]
> the same problem , have you solved it.

me too, did you guys solve it?

**Comment by ArghyaChatterjee** [comment]
The problem has been solved. Sorry I didn't have enough time as I was busy with my projects. Just do a fresh clone on ros melodic and follow the instruction for build from the readme file.
